//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchCRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebResource
    {
        public string ModifiedOnBehalfByYomiName { get; set; }
        public string CreatedOnBehalfByYomiName { get; set; }
        public string ModifiedOnBehalfByName { get; set; }
        public string CreatedOnBehalfByName { get; set; }
        public string OrganizationIdName { get; set; }
        public System.Guid WebResourceId { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public string SilverlightVersion { get; set; }
        public int WebResourceType { get; set; }
        public System.Guid OrganizationId { get; set; }
        public System.Guid SolutionId { get; set; }
        public Nullable<System.Guid> SupportingSolutionId { get; set; }
        public System.DateTime OverwriteTime { get; set; }
        public int ComponentState { get; set; }
        public byte[] VersionNumber { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public System.Guid WebResourceIdUnique { get; set; }
        public Nullable<System.Guid> ModifiedOnBehalfBy { get; set; }
        public Nullable<System.Guid> CreatedOnBehalfBy { get; set; }
        public Nullable<int> LanguageCode { get; set; }
        public bool IsManaged { get; set; }
        public bool IsCustomizable { get; set; }
        public bool CanBeDeleted { get; set; }
        public bool IsHidden { get; set; }
        public string IntroducedVersion { get; set; }
        public bool IsEnabledForMobileClient { get; set; }
    }
}
